python_lab_project/python_lab_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexPageView.as_view(), name='index'),

]

python_lab_project/python_lab_project/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from python_lab_app import views

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
                            # Change the admin prefix here to use an alternate URL for the
                            # admin interface, which would be marginally more secure.
                            ("^admin/", include(admin.site.urls)),
                            )

if settings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
                            url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),

                            )

urlpatterns += patterns('',
                        # We don't want to presume how your homepage works, so here are a
                        # few patterns you can use to set it up.

                        # HOMEPAGE AS STATIC TEMPLATE
                        # ---------------------------
                        # This pattern simply loads the index.html template. It isn't
                        # commented out like the others, so it's the default. You only need
                        # one homepage pattern, so if you use a different one, comment this
                        # one out.

                        url("^$", views.IndexPageView.as_view(), name="home"),

                        # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
                        # ---------------------------------------------
                        # This pattern gives us a normal ``Page`` object, so that your
                        # homepage can be managed via the page tree in the admin. If you
                        # use this pattern, you'll need to create a page in the page tree,
                        # and specify its URL (in the Meta Data section) as "/", which
                        # is the value used below in the ``{"slug": "/"}`` part.
                        # Also note that the normal rule of adding a custom
                        # template per page with the template name using the page's slug
                        # doesn't apply here, since we can't have a template called
                        # "/.html" - so for this case, the template "pages/index.html"
                        # should be used if you want to customize the homepage's template.

                        # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

                        # HOMEPAGE FOR A BLOG-ONLY SITE
                        # -----------------------------
                        # This pattern points the homepage to the blog post listing page,
                        # and is useful for sites that are primarily blogs. If you use this
                        # pattern, you'll also need to set BLOG_SLUG = "" in your
                        # ``settings.py`` module, and delete the blog page object from the
                        # page tree in the admin if it was installed.

                        # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

                        # MEZZANINE'S URLS
                        # ----------------
                        # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
                        # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
                        # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
                        # WILL NEVER BE MATCHED!

                        # If you'd like more granular control over the patterns in
                        # ``mezzanine.urls``, go right ahead and take the parts you want
                        # from it, and use them directly below instead of using
                        # ``mezzanine.urls``.
                        ("^", include("mezzanine.urls")),

                        # MOUNTING MEZZANINE UNDER A PREFIX
                        # ---------------------------------
                        # You can also mount all of Mezzanine's urlpatterns under a
                        # URL prefix if desired. When doing this, you need to define the
                        # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
                        # SITE_PREFIX = "my/site/prefix"
                        # For convenience, and to avoid repeating the prefix, use the
                        # commented out pattern below (commenting out the one above of course)
                        # which will make use of the ``SITE_PREFIX`` setting. Make sure to
                        # add the import ``from django.conf import settings`` to the top
                        # of this file as well.
                        # Note that for any of the various homepage patterns above, you'll
                        # need to use the ``SITE_PREFIX`` setting as well.

                        # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

                        )


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
# handler404 = "mezzanine.core.views.page_not_found"
# handler500 = "mezzanine.core.views.server_error"
handler404 = "python_lab_app.views.handler404"
handler500 = "python_lab_app.views.handler500"

if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += patterns('',
            url(r'^python_lab_app/static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^bower_components/static/seiyria-bootstrap-slider/css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^bower_components/static/bootstrap/dist/css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),


    )
urlpatterns += static('/bower_components/', document_root=settings.PROJECT_ROOT + '/bower_components/')

python_lab_project/python_lab_app/models.py
from django.db import models
from mezzanine.core.models import RichTextField
import django.utils.timezone


class Skill(models.Model):
    title = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.title


class Mark(models.Model):
    title = models.ForeignKey('Skill')
    value = models.PositiveIntegerField(default=1)

    def __unicode__(self):
        return self.title.title + ': ' + str(self.value)


class Applicant(models.Model):
    name = models.CharField(max_length=30, verbose_name='First name')
    surname = models.CharField(max_length=30, verbose_name='Last name')
    email = models.EmailField(max_length=50, verbose_name='E-mail address')
    phone_number = models.CharField(max_length=20, verbose_name='Phone number')
    age = models.PositiveIntegerField()
    mark = models.ManyToManyField('Mark')
    is_student = models.BooleanField(verbose_name='Student')
    is_job_applicant = models.BooleanField(verbose_name='Job applicant')
    application_data = models.DateTimeField(default=django.utils.timezone.now)

    def __unicode__(self):
        return self.name + ' ' + self.surname


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    title = models.CharField(max_length=100, unique=False, )

    def __unicode__(self):
        return self.title


class Subcategory(models.Model):
    title = models.CharField(max_length=100, unique=False)
    category = models.ForeignKey("Category")

    def __unicode__(self):
        return self.title


class Point(models.Model):
    title = models.TextField(max_length=300, unique=False)
    subcategory = models.ForeignKey("Subcategory", blank=True, null=True)

    def __unicode__(self):
        return self.title


class Paragraph(models.Model):
    title = models.CharField(max_length=50)
    text = RichTextField()

    def __unicode__(self):
        return self.title


class Recipient(models.Model):
    email = models.EmailField(max_length='50',  verbose_name='E-mail address', unique=True, null=False)

    def __unicode__(self):
        return self.email


class Message(models.Model):
    title = models.CharField(unique=True, max_length=100)
    text = RichTextField()

    def __unicode__(self):
        return self.title

python_lab_project/python_lab_app/forms.py
from django import forms

from python_lab_app import models


class ApplicantForm(forms.ModelForm):
    class Meta:
        model = models.Applicant
        exclude = ['application_data', 'mark', ]

python_lab_project/python_lab_app/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
from django.template import RequestContext

from python_lab_app import forms, models


class IndexPageView(FormView):
    template_name = "main.html"
    form_class = forms.ApplicantForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        paragraphs = models.Paragraph.objects.all()
        categories = models.Category.objects.all()
        subcategories = models.Subcategory.objects.all()
        points = models.Point.objects.all()
        skills = models.Skill.objects.all().order_by('title')
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context['paragraphs'] = paragraphs
        context['categories'] = categories
        context['subcategories'] = subcategories
        context['points'] = points
        context['skills'] = skills
        return context

    def form_valid(self, form):
        applicant = form.save()
        for key in form.data.keys():
            if key[:5] == 'mark_':
                skill = models.Skill.objects.get(title=key[5:])
                mark = models.Mark.objects.create(title=skill, value=int(form.data[key]))
                applicant.mark.add(mark)

        # html_template = get_template('email.html')
        # d = Context({'applicant': applicant, 'phone': applicant.phone_number,
        #              'email': applicant.email})
        #
        # html_content = html_template.render(d)
        # recipients = list()
        # for recipient in models.Recipient.objects.all():
        #     recipients.append(recipient.email)
        #
        # msg = EmailMultiAlternatives('Python Lab Application: ' + str(applicant), '', 'polyashinkarenko@gmail.com',
        #                              recipients)
        # msg.attach_alternative(html_content, "text/html")
        # msg.send()
        context = self.get_context_data()
        context['message'] = models.Message.objects.get(title='SUCCESSFUL_REGISTRATION')
        return render(self.request, self.template_name, context)


def handler404(request):
    response = render_to_response('404.html', {'message': models.Message.objects.get(title='NOT_FOUND')},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {'message': models.Message.objects.get(title='INTERNAL_SERVER_ERROR')},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

python_lab_project/python_lab_app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-language" content="en">

    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}

    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/Light-IT-logo.ico" %}"/>
    <link href="../../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="../../bower_components/seiyria-bootstrap-slider/css/bootstrap-slider.css" rel="stylesheet">


    <link rel="stylesheet" type="text/css"
          href="{% static "textinputeffects/fonts/font-awesome-4.2.0/css/font-awesome.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "textinputeffects/css/set1.css" %}"/>
    <link href="{% static "css/index.css" %}" rel="stylesheet">

    <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
    <script src="../../bower_components/seiyria-bootstrap-slider/js/bootstrap-slider.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{% static "js/jquery.sticky.js" %}"></script>
    <script type="text/javascript"
            src="http://digitalbush.com/wp-content/uploads/2013/01/jquery.maskedinput-1.3.1.min_.js"></script>
    <script type="text/javascript" src="{% static "js/page-load.js" %}"></script>

    <script type="text/javascript" src="{% static "textinputeffects/js/classie.js" %}"></script>


    <title>{% block title %}Python Lab | Курсы программирования на языке Python от компании
        Light-IT    {% endblock %}</title>

</head>
<body>


{% block start %}
    <div id="header" class="header">

        <img src={% static "img/Light-IT1.png" %}>
        {% block buttonToDown %}

        {% endblock %}
    </div>

{% endblock %}

{% if message %}
    <div class="popup" id="{{ message.title }}">

        <p>{{ message.text | safe }}</p>
    </div>
{% endif %}


{% block content %}
{% endblock %}

</body>
</html>

python_lab_project/python_lab_app/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div>
    <p><b>Applicant: </b>  {{ applicant }}</p>
    <p><b>Phone: </b>  {{ phone }}</p>
    <p><b>Email: </b>  {{ email }}</p>
</div>



</body>
</html>

python_lab_project/python_lab_app/templates/main.html
{% extends "base_template.html" %}
{% load staticfiles %}


{% block buttonToDown %}
    <div id="toElemButton"><a id="toElem" class="scroll-down scroll-to bounce">
        <span class="fa fa-angle-down animated bounce" data-effect="bounce"></span>
    </a></div>
{% endblock %}

{% block content %}
    <div class="sticky-menu" id="sticker">
        <div class="row row-header">

            <img id="toHome" src={% static "img/Light-IT.png" %}>

            <span id="toRegistrationForm">ЗАРЕГИСТРИРОВАТЬСЯ СЕЙЧАС</span>

        </div>
    </div>



    <div class="container-fluid">
        <div class="col-md-12">

            {% for paragraph in paragraphs %}
                <div class="row row-context">
                    <div class="paragraph-container">
                        {% if forloop.counter == 1 %}
                            <img src="{% static "img/HYk1WIb.png" %}">
                        {% endif %}

                        <div>{{ paragraph.title }}</div>
                    </div>
                </div>
                <div class="paragraph-text"> {{ paragraph.text | safe }}</div>
                {% if forloop.counter == 2 %}
                    <div class="table-responsive-style">
                        <table class="table table-bordered">
                            {% for category in categories %}


                                <thead>
                                <tr>
                                    <td colspan="2">
                                        {{ category.title }} </td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for subcategory in category.subcategory_set.all %}
                                    <tr>

                                        <td>{{ subcategory }}</td>

                                        <td>
                                            <ul>
                                                {% for point in subcategory.point_set.all %}
                                                    <li>{{ point }}</li>
                                                {% endfor %}
                                            </ul>
                                        </td>


                                    </tr>
                                {% endfor %}
                                </tbody>

                            {% endfor %}
                        </table>
                    </div>
                {% endif %}
            {% endfor %}


            <div id="registrationForm" class="form-wrapper">
                <form action="" method="post" id="id_questionnaire" name="questionnaire">
                    {% csrf_token %}
                    <h3>Расскажите о себе:</h3>


                    <div class="row">
                        <div class="group group-left-part">

                <span class="input input--hoshi">
					<input name="name" class="input__field input__field--hoshi" type="text" id="id_name"
                           maxlength="30" required/>
					<label class="input__label input__label--hoshi input__label--hoshi-color-1" for="id_name">
                        <span class="input__label-content input__label-content--hoshi">Имя</span>
                    </label>
				</span>
                        </div>
                        <div class="group group-right-part">
                       <span class="input input--hoshi">
					<input name="surname" class="input__field input__field--hoshi" type="text" id="id_surname"
                           maxlength="30" required/>
					<label class="input__label input__label--hoshi input__label--hoshi-color-1" for="id_surname">
                        <span class="input__label-content input__label-content--hoshi">Фамилия</span>
                    </label>
				</span>
                        </div>
                    </div>
                    <div class="row group">
                    <span class="input input--hoshi">
					<input name="email" class="input__field input__field--hoshi" type="email" id="id_email"
                           maxlength="50" required/>
					<label class="input__label input__label--hoshi input__label--hoshi-color-1" for="id_email">
                        <span class="input__label-content input__label-content--hoshi">Email</span>

                    </label>
				</span>


                    </div>

                    <div class="row group">
                                       <span class="input input--hoshi">
					<input name="phone_number" class="input__field input__field--hoshi" type="text" id="id_tel"
                           maxlength="10"/>
					<label class="input__label input__label--hoshi input__label--hoshi-color-1" for="id_tel">
                        <span class="input__label-content input__label-content--hoshi">Телефон</span>

                    </label>
				</span>


                    </div>

                    <div class="row">

                    </div>


                    <div class="row group slider-row">
                        <div class="slider-title">Возраст</div>
                        <div class="slider-group">

                            <div class="range">
                                <input id="id_age" name="age" type="range" min="18" max="30" value="24"
                                       onchange="age_range.value=value">
                                <output id="age_range">24</output>

                            </div>

                        </div>
                    </div>

                    <h3>Оцените свои знания по пятибальной шкале:</h3>

                    <h3 class="sub-h3">1 - слышал название, 5 - знаю всё</h3>
                    {% for skill in skills %}

                        <div class="row group slider-row">
                            <div class="slider-title">{{ skill }}</div>
                            <div class="slider-group">

                                <div class="range">
                                    <input id="id_{{ skill }}" name="mark_{{ skill }}" type="range" min="1" max="5"
                                           value="3"
                                           onchange="{{ skill }}_range.value=value">
                                    <output id="{{ skill }}_range">3</output>

                                </div>

                            </div>
                        </div>



                    {% endfor %}
                    <div id="checkbox-group" class="row">

                        <div class="col-sm-6"><label class="checkbox-label"><input type="checkbox"
                                                                                                   id="id_student"
                                                                                                   name="is_student">Я
                            студент</label></div>

                        <div class="col-sm-6"><label class="checkbox-label"><input type="checkbox"
                                                                                                  id="id_job_applicant"
                                                                                                  name="is_job_applicant">Я
                            хочу у вас
                            работать</label></div>


                    </div>
                    <button id="save" class="btn btn-primary btn-block btn-lg" type="submit" name="submit"
                            tabindex="13">
                        Присоединиться
                    </button>
                </form>
            </div>

            <div class="footer">

                <a href="http://light-it.net/" target="_blank">
                    <img src={% static "img/Light-IT1.png" %}>
                </a>

                <p>
                    You Gotta Love
                    <a href="https://www.python.org/" target="_blank">Python</a>
                </p>
            </div>
        </div>
    </div>
    <a href="#" class="back-to-top" onfocus="this.blur();"><span>&#94;</span></a>

{% endblock %}