scribbling_diary/notes/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from . import views


urlpatterns = [
    url(r'^$', views.IndexPageView.as_view(), name='index'),
    url(r'^register/$', views.RegisterUserView.as_view(), name='register'),
    url(r'^profile/$', views.ProfilePageView.as_view(), name='profile'),
    url(r'^add_note/$', views.AddNoteView.as_view(), name='add_note'),
    url(r'^del_note/$', views.DeleteNoteView.as_view(), name='del_note'),
    url(r'^edit_note/$', views.EditNoteView.as_view(), name='edit_note'),
    url(r'^category_search/(?P<category>\w+)/$', views.CategorySearchView.as_view(),
        name='category_search'),
    url(r'^tag_search/(?P<tag>\w+)/$', views.TagSearchView.as_view(), name='tag_search'),
    url(r'^get_note/(?P<note_id>[0-9]+)/$', views.GetNoteView.as_view(), name='get_note'),
    url(r'^i_read/$', views.IReadView.as_view(), name='i_read'),
    url(r'^define_friends/$', views.DefineFriendsView.as_view(), name='define_friends'),
    url(r'^search_notes/$', views.SearchNotesView.as_view(), name='search_notes'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

scribbling_diary/scribbling_diary/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from notes.views import *

urlpatterns = [
    url(r'^', include('notes.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', LoginFormView.as_view()),
    url(r'^logout/$', LogoutView.as_view()),

]

scribbling_diary/notes/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import mptt
from django.utils import timezone

white_color = '#FFFFFF'
black_color = '#000000'


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, password=None, **kwargs):
        if not kwargs.get('username'):
            raise ValueError('User must have a valid username.')

        account = self.model(username=kwargs.get('username'))

        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, password, **kwargs):
        account = self.create_user(password, **kwargs)

        account.is_staff = True
        account.is_superuser = True
        account.save()

        return account


class Account(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=40, unique=True)
    is_staff = models.BooleanField(default=False)
    account_friends = models.ManyToManyField('self', blank=True, through='Friend', symmetrical=False)

    objects = AccountManager()

    USERNAME_FIELD = 'username'

    def __unicode__(self):
        return self.username

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    title = models.CharField('Title', max_length=100)
    parent = models.ForeignKey('self', blank=True, null=True, verbose_name="parent", related_name='child')

    def __unicode__(self):
        return self.title


mptt.register(Category, )


class Tag(models.Model):
    title = models.CharField(max_length=50)

    def __unicode__(self):
        return self.title


class Color(models.Model):
    title = models.CharField('Title', max_length=30)
    value = models.CharField('Value', max_length=7, default=white_color, unique=True)

    def __unicode__(self):
        return self.title


class Note(models.Model):
    title = models.CharField('Title', max_length=100)
    text = models.TextField('Text', max_length=1500, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    background_color = models.ForeignKey(Color, blank=True, related_name='note_background_color')
    text_color = models.ForeignKey(Color, blank=True, related_name='note_text_color')
    pub_date = models.DateTimeField('date published', default=timezone.now)
    permission = models.ManyToManyField(Account, through='Permission')
    image = models.ImageField(blank=True, upload_to='pictures_folder/')

    def __unicode__(self):
        return self.title

    def get_background_color(self):
        return white_color if self.background_color is None else self.background_color

    def get_text_color(self):
        return black_color if self.text_color is None else self.text_color


class Permission(models.Model):
    user = models.ForeignKey(Account)
    note = models.ForeignKey(Note, related_name='note_account_permissions')

    ACCESS_CHOICES = (
        ('A', 'Author'),
        ('R', 'Reader'),
        ('W', 'Writer'),
    )
    access = models.CharField(max_length=1, choices=ACCESS_CHOICES, default='A')

    def __unicode__(self):
        return self.note.title


class Friend(models.Model):
    user = models.ForeignKey(Account)
    friend = models.ForeignKey(Account, related_name='user_friend')

scribbling_diary/notes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from notes.models import *


class ColorForm(forms.ModelForm):
    value = forms.RegexField(regex='[#][a-fA-F0-9]+')


class MyRegistrationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ('username', 'password1', 'password2')

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)

        if commit:
            user.save()
        return user


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        exclude = ['permission', 'tags', 'pub_date']

scribbling_diary/notes/views.py
from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.base import *
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from notes.forms import *


class ContextMixin(object):
    @classmethod
    def get_context(cls, request, context):
        context['tags'] = Tag.objects.all()
        context['categories'] = Category.objects.all()
        context['colors'] = Color.objects.all()
        context['category_choosing'] = Category.objects.exclude(parent=None)
        context['users'] = Account.objects.exclude(username=request.user.username).exclude(is_superuser=True)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class RegisterUserView(FormView):
    form_class = MyRegistrationForm

    template_name = "notes/register.html"

    success_url = "/profile"

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterUserView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "notes/login.html"
    success_url = "/profile"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    @staticmethod
    def get(request):
        logout(request)
        return HttpResponseRedirect("/", {})


class IndexPageView(TemplateView):
    template_name = "notes/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context['images'] = [[str(i + 3 * (j - 1)) for i in xrange(1, 4)] for j in xrange(1, 4)]
        titles = ['Explore yourself', 'Enjoy yourself', 'Express yourself']
        for i, title in enumerate(titles):
            context['images'][i].insert(0, title)
        return context


class ProfilePageView(LoginRequiredMixin, ContextMixin, TemplateView):
    template_name = 'notes/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfilePageView, self).get_context_data(**kwargs)
        user_notes = Note.objects.filter(permission=self.request.user, note_account_permissions__access='A')
        self.get_context(self.request, context)
        context['notes'] = user_notes
        if len(user_notes) > 0:
            context['note'] = user_notes[0]
            context['readers'] = Account.objects.filter(note=user_notes[0], permission__access='R')
        else:
            context['note'] = None
            context['readers'] = None
        return context


class AddNoteView(FormView):
    form_class = NoteForm
    template_name = 'notes/profile.html'
    success_url = "/profile"

    def form_valid(self, form):
        note = form.save()

        Permission.objects.create(user=self.request.user, note=note, access='A')
        tag_list = self.request.POST.getlist('tags')

        for tag in tag_list:
            new_tag = Tag.objects.get_or_create(title=tag)
            note.tags.add(new_tag[0])

        readers_list = self.request.POST.getlist('readers')
        for person in readers_list:
            reader = Account.objects.get(id=person)
            Permission.objects.create(user=reader, note=note, access='R')
        return super(AddNoteView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponseRedirect('/profile', {})


class DeleteNoteView(View):
    template_name = 'notes/profile.html'

    @staticmethod
    def post(request):
        note_list = request.POST.getlist('note')
        for note in note_list:
            Note.objects.filter(id=note).delete()
        return HttpResponseRedirect('/profile', {})


class EditNoteView(FormView):
    template_name = 'notes/profile.html'
    success_url = "/profile"

    def form_valid(self, form):
        note = form.save()
        for category in note.categories.all():
            note.categories.remove(category)
        note.categories.add(*self.request.POST.getlist('categories'))

        for tag in note.tags.all():
            note.tags.remove(tag)
        tag_list = self.request.POST.getlist('tags')
        for tag in tag_list:
            new_tag = Tag.objects.get_or_create(title=tag)
            note.tags.add(new_tag[0])

        note.pub_date = timezone.now()

        Permission.objects.filter(note=note, access='R').delete()
        readers = self.request.POST.getlist('readers')
        for person in readers:
            reader = Account.objects.get(id=person)
            Permission.objects.create(user=reader, note=note, access='R')
        return super(EditNoteView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponseRedirect('/profile', {})

    def get_form(self, form_class=None):
        note_id = self.request.POST['note']
        note = Note.objects.get(id=note_id)
        form = NoteForm(self.request.POST, self.request.FILES, instance=note)
        return form


class CategorySearchView(ContextMixin, TemplateView):
    template_name = 'notes/search_notes.html'

    def get(self, request, **kwargs):
        user_notes = Note.objects.filter(Q(permission=request.user), Q(note_account_permissions__access='A') |
                                         Q(note_account_permissions__access='R'))
        result_notes = []
        for note in user_notes:
            note_categories = Category.objects.filter(note=note)
            for current_category in note_categories:
                self.search_categories(note=note, current_category=current_category, category=kwargs['category'],
                                       result_notes=result_notes)
        context = dict()
        self.get_context(request, context)
        context['notes'] = result_notes
        if kwargs['category'] == 'all':
            context['notes'] = user_notes
        return self.render_to_response(context)

    def search_categories(self, **kwargs):
        current_category = kwargs['current_category']
        category = kwargs['category']
        note = kwargs['note']
        result_notes = kwargs['result_notes']
        if str(current_category) == str(category) and note not in result_notes:
            result_notes.append(note)
        if current_category.parent is None:
            return result_notes
        else:
            return self.search_categories(note=note, current_category=current_category.parent, category=category,
                                          result_notes=result_notes)


class TagSearchView(ContextMixin, TemplateView):
    template_name = 'notes/search_notes.html'

    def get(self, request, **kwargs):
        user_notes = Note.objects.filter(Q(permission=request.user), Q(note_account_permissions__access='A') |
                                         Q(note_account_permissions__access='R'))
        result_notes = []
        for note in user_notes:
            note_tags = Tag.objects.filter(note=note)
            for current_tag in note_tags:
                if str(current_tag) == str(kwargs['tag']) and current_tag not in result_notes:
                    result_notes.append(note)
        context = dict()
        self.get_context(request, context)
        context['notes'] = result_notes
        return self.render_to_response(context)


class GetNoteView(ContextMixin, TemplateView):
    template_name = 'notes/load_note.html'

    def get_context_data(self, **kwargs):
        note = Note.objects.get(id=kwargs['note_id'])
        context = super(GetNoteView, self).get_context_data(**kwargs)
        self.get_context(self.request, context)
        context['note'] = note
        context['readers'] = Account.objects.filter(note=note, permission__access='R')
        return context


class IReadView(LoginRequiredMixin, ContextMixin, TemplateView):
    template_name = 'notes/i_read.html'

    def get_context_data(self, **kwargs):
        all_notes = Note.objects.filter(permission=self.request.user, note_account_permissions__access='R')
        context = super(IReadView, self).get_context_data(**kwargs)
        self.get_context(self.request, context)
        context['notes'] = all_notes
        context['authors'] = []
        for note in all_notes:
            context['authors'].append(
                {'note': note.id, 'author': Account.objects.get(note=note, permission__access='A').username})
        return context


class DefineFriendsView(View):
    @staticmethod
    def post(request):
        user = Account.objects.get(username=request.user)
        Friend.objects.filter(user=request.user).delete()
        new_friend_list = request.POST.getlist('friends')
        for person in new_friend_list:
            friend = Account.objects.get(id=person)
            Friend.objects.create(user=user, friend=friend)
        return HttpResponseRedirect('/profile', {})


class SearchNotesView(LoginRequiredMixin, ContextMixin, View):
    template_name = 'notes/search_notes.html'

    def post(self, request):
        context = dict()
        self.get_context(request, context)
        search_result = []
        user_note_check = request.POST.getlist('user_notes_check')
        read_note_check = request.POST.getlist('read_notes_check')

        if len(user_note_check) > 0 >= len(read_note_check):
            notes = Note.objects.filter(permission=request.user, note_account_permissions__access="A")

        elif len(read_note_check) > 0 >= len(user_note_check):

scribbling_diary/notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-language" content="en">

    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <title>SDiary | {% block title %}{% endblock %} </title>
    <link href="{% static "notes/bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "notes/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/base.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/carousel.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/header.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/authorization.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/footer.css" %}" rel="stylesheet">
    <link href="{% static "notes/css/notes.css" %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "notes/bootstrap/js/bootstrap.js" %}" type="text/javascript"></script>

    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script src="{% static "notes/bootstrap/js/select.js" %}" type="text/javascript"></script>


    <link href="{% static "notes/bootstrap/css/bootstrap-tag-cloud.css" %}" rel="stylesheet">
    <script src="{% static "notes/bootstrap/js/bootstrap-tag-cloud.js" %}" type="text/javascript"></script>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <div class="brand">

                {% if user.is_authenticated %}
                    {{ user }}'s
                {% else %}
                    Your
                {% endif %}
                Scribbling Diary

            </div>
            <div id="navbar" class=" nav-collapse">

                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>

                    {% if user.is_authenticated %}
                        <li><a href="/profile">Diary</a></li>
                        <li><a href="/logout">Log Out</a></li>

                    {% else %}

                        <li><a href="/login">Log In&nbsp;</a></li>


                    {% endif %}

                    <li><a href="/">Contact</a></li>
                </ul>
            </div>

        </div>
    </div>

</div>

<div class="container container-style">
    {% block content %}Empty page{% endblock %}
</div>
<footer class="footer">
    <div class="container">
        <p class="text-muted">Made in Ukraine <br>© 2015</p>
    </div>
</footer>


</body>
</html>

scribbling_diary/notes/templates/notes/i_read.html
{% extends 'notes/profile.html' %}
{% block title %}Reading{% endblock %}
{% block header %}
    Notes for reading
{% endblock %}
{% block all_categories %}
    <li class="all">
        <ul><label class="all-categories">All categories <a class="tree-toggler"
                                                            href="{% url 'category_search'  'all' %}">&emsp;&#8811;</a></label>
        </ul>
    </li>
{% endblock %}

{% block button_available %}
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Add
        </button>
    </div>
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Delete
        </button>
    </div>
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Edit
        </button>
    </div>
{% endblock %}

{% block button-read %}
    <button class="btn btn-lg btn-primary-control btn-block " onclick="location.href='/profile'" type="button">My
        notes
    </button>
{% endblock %}

{% block author %}

    {% for item in authors %}
        <div class="author-block">
            {% if note.id == item.note %}
                Author: {{ item.author }}
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}


{% block tag_search_note %}
    <a href="{% url 'tag_search'  tag.title %}">#{{ tag.title }}</a>
{% endblock %}

{% block tag_search_cloud %}
    <a href="{% url 'tag_search'  tag.title  %}">
{% endblock %}

{% block category_search_list %}
    <a class="tree-toggler" href="{% url 'category_search'  node.title   %}">
{% endblock %}

{% block category_search_note %}
    <a href="{% url 'category_search'  category.title  %}">
{% endblock %}

scribbling_diary/notes/templates/notes/index.html
{% extends 'notes/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    {% load staticfiles %}



    <link rel="stylesheet" href="{% static "notes/css/flexslider.css" %}" type="text/css" media="screen">
    <script src="{% static "notes/js/jquery.flexslider.js" %}" type="text/javascript"></script>
    <script src="{% static "notes/js/carousel.js" %}" type="text/javascript"></script>

    <h1 class="h-title">Create your own Diary. Try it.</h1>
    <div class="flexslider">
        <ul class="slides">
            {% for row in images %}
                {% for image in row %}
                    {% if forloop.counter != 1 %}
                        {% with "notes/images/"|add:image|add:".jpg" as src %}
                            <li><img src="{% static src %}" class="tr-images" alt="Image{{ image }}">
                                {% if forloop.counter == 2 %}
                                    <p class="flex-caption">{{ row.0 }}</p>
                                {% endif %}


                            </li>
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </ul>
    </div>

{% endblock %}

scribbling_diary/notes/templates/notes/load_note.html
<form enctype="multipart/form-data"  method="post" action="" >
    <input class="form-control note-title-input " type="text" id="id_title_get" maxlength="20"
           name="title" placeholder="Title" required autofocus value="{{ note.title }}"/>
                <textarea maxlength="1500" class="form-control" style="resize: none" rows="10" cols="45" id="id_text"
                          name="text">{{ note.text }}</textarea>

    <p>
        {% if note.image %}
            <div class="image-small-container"><img class="note-image thumbnail" src="{{ note.image.url }}"/></div>
            <p>You may change the image</p>
        {% endif %}
    <input id="id_image" type="file" class="" name="image">

    </p>

    <p>Tags for your note</p>

    <p><select style="width: 100%;" class="js-example-tags" multiple="multiple" name="tags" id="id_tags">
        {% for tag in tags %}

            {% if tag in note.tags.all %}
                <option selected value="{{ tag.title }}">{{ tag.title }}</option>
            {% else %}
                <option value="{{ tag.title }}">{{ tag.title }}</option>
            {% endif %}
        {% endfor %}
    </select></p>
    <p>Categories for your note</p>

    <p><select style="width: 100%;" class="js-example-basic-multiple" multiple="multiple" name="categories"
               id="id_categories">
        {% for category in category_choosing %}
            {% if category in note.categories.all %}
                <option selected value="{{ category.id }}">{{ category.title }}</option>

            {% else %}
                <option value="{{ category.id }}">{{ category.title }}</option>
            {% endif %}
        {% endfor %}
    </select></p>
    <p>Your note color</p>

    <p><select style="width: 100%;" class="js-example-basic-single select-color" name="background_color"
               id="id_background_color">
        {% for color in colors %}

            {% if color == note.background_color %}
                <option selected value="{{ color.id }}">{{ color.title }}</option>

            {% else %}
                <option value="{{ color.id }}">{{ color.title }}</option>
            {% endif %}
        {% endfor %}
    </select></p>
    <p>Your text color</p>

    <p><select style="width: 100%;" class="js-example-basic-single" name="text_color" id="id_text_color">
        {% for color in colors %}

            {% if color == note.text_color %}
                <option selected value="{{ color.id }}">{{ color.title }}</option>

            {% else %}
                <option value="{{ color.id }}">{{ color.title }}</option>
            {% endif %}
        {% endfor %}
    </select></p>

    <p>Readers</p>

    <p><select style="width: 100%;" class="js-example-responsive" multiple="multiple" name="readers"
               id="id_friends">

        {% if user.account_friends.all|length > 0 %}
            <optgroup label="Friends">
                {% for person in user.account_friends.all %}
                    {% if person in readers %}

                        <option selected value="{{ person.id }}">{{ person.username }}</option>
                    {% else %}
                        <option value="{{ person.id }}">{{ person.username }}</option>
                    {% endif %}
                {% endfor %}
            </optgroup>
        {% endif %}
        {% if users.all|length > 0 %}
            <optgroup label="Other">
                {% for person in users %}
                    {% if person not in user.account_friends.all %}
                        {% if person in readers %}
                            <option selected value="{{ person.id }}">{{ person.username }}</option>
                        {% else %}
                            <option value="{{ person.id }}">{{ person.username }}</option>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </optgroup>
        {% endif %}
    </select></p>
</form>

scribbling_diary/notes/templates/notes/login.html
{% extends 'notes/base.html' %}
{% block title %}Log In{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-signin container-top" action="" method="post">
            <h2 class="form-signin-heading">Please log in</h2>
            {% csrf_token %}
            <input type="text" id="id_username" class="form-control" maxlength="30" name="username"
                   placeholder="Username" required autofocus/>
            <input type="password" id="id_password1" name="password" class="form-control" placeholder="Password"
                   required/>


            <button class="btn btn-lg btn-primary btn-block " type="submit">Log In</button>

            {% for error in form.non_field_errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% for error in  form.username.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% for error in  form.password.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}

        </form>
    </div>

    <div class="container ">
        <div class="form-signin container-bottom">
            <h3 class="form-signin-heading">Not registered yet?</h3>
            {% csrf_token %}
            <form action="/register">
                <button class="btn btn-lg btn-primary btn-block " type="submit">Register</button>
            </form>

        </div>
    </div>

{% endblock %}

scribbling_diary/notes/templates/notes/register.html
{% extends 'notes/base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
    <div class="container">
        <form class="form-signin" action="" method="post">
            <h2 class="form-signin-heading">Sign Up</h2>
            {% csrf_token %}


            <input type="text" id="id_username" class="form-control" maxlength="15" name="username"
                   placeholder="Username" required autofocus/>
            <input type="password" id="id_password1" name="password1" class="form-control middlefield"
                   placeholder="Password" required/>
            <input type="password" id="id_password2" name="password2" class="form-control"
                   placeholder="Re-enter password" required/>


            <button class="btn btn-lg btn-primary btn-block " type="submit">Sign Up</button>

            {% for error in form.non_field_errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% for error in  form.username.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% for error in  form.password1.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
            {% for error in  form.password2.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}


        </form>
    </div>


{% endblock %}

scribbling_diary/notes/templates/notes/search_notes.html
{% extends 'notes/profile.html' %}
{% block title %}Searching{% endblock %}
{% block header %}
    Searching results
{% endblock %}

{% block all_categories %}
    <li class="all">
        <ul><label class="all-categories">All categories <a class="tree-toggler"
                                                            href="{% url 'category_search'  'all'  %}">&emsp;&#8811;</a></label>
        </ul>
    </li>
{% endblock %}

{% block button_available %}
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Add
        </button>
    </div>
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Delete
        </button>
    </div>
    <div class="button-div">
        <button class="btn btn-lg btn-primary-control btn-block " disabled type="button">Edit
        </button>
    </div>
{% endblock %}



{% block author %}

    {% for item in authors %}
        <div class="author-block">
            {% if note.id == item.note %}
                Author: {{ item.author }}
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

{% block tag_search_note %}
    <a href="{% url 'tag_search'  tag.title  %}">#{{ tag.title }}</a>
{% endblock %}

{% block tag_search_cloud %}
    <a href="{% url 'tag_search'  tag.title  %}">
{% endblock %}

{% block category_search_list %}
    <a class="tree-toggler" href="{% url 'category_search'  node.title   %}">
{% endblock %}

{% block category_search_note %}
    <a href="{% url 'category_search'  category.title  %}">
{% endblock %}